spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: rushi
    url: jdbc:h2:mem:testdb
    username: rushi
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
      
